from src.core.types import GENERIC_PAGE_TOPIC_FALLBACK, PagePlan, PageUnderstanding


class PagePlanBuilder:
    def build(self, understanding: PageUnderstanding) -> PagePlan:
        return PagePlan(
            page_topic=understanding.page_topic,
            page_goal=understanding.page_goal,
            hero=self.build_hero(understanding),
            main_sections=self.build_main_sections(understanding),
            supporting_elements=self.build_supporting_elements(understanding),
            visual_direction=self.build_visual_direction(understanding),
            layout_advice=self.build_layout_advice(understanding),
            interaction_hint=self.build_interaction_hint(understanding),
            starter_html=self.build_starter_html(understanding),
        )

    def build_hero(self, understanding: PageUnderstanding) -> str:
        if understanding.page_type == "teaching_page":
            return f"用明确标题、简短导语和一个引导阅读的首屏，快速说明 {understanding.page_topic} 为什么值得理解。"
        if understanding.page_type == "summary_page":
            return f"用总结标题、阶段概览和一句重点提示，先把 {understanding.page_topic} 的整体轮廓立住。"
        if understanding.page_type == "landing_page":
            return f"用强标题、亮点副标题和主按钮，把 {understanding.page_topic} 的吸引力先打出来。"
        if understanding.page_topic == GENERIC_PAGE_TOPIC_FALLBACK:
            return "先用页面标题和简短导语说明当前页面要解决什么展示任务。"
        return f"用页面标题、简短说明和概览信息，先把 {understanding.page_topic} 的核心展示目标说清楚。"

    def build_main_sections(self, understanding: PageUnderstanding) -> str:
        if understanding.page_type == "teaching_page":
            return "建议拆成概念介绍、关键知识点、例子说明三个主体区块。"
        if understanding.page_type == "summary_page":
            return "建议拆成重点回顾、结构梳理、结论总结三个主体区块。"
        if understanding.page_type == "landing_page":
            return "建议拆成核心卖点、亮点展示、行动引导三个主体区块。"
        return "建议拆成核心内容展示、重点信息卡片、结果总结三个主体区块。"

    def build_supporting_elements(self, understanding: PageUnderstanding) -> str:
        if understanding.page_type == "teaching_page":
            return "可以补充导航锚点、知识标签、延伸阅读或练习入口。"
        if understanding.page_type == "summary_page":
            return "可以补充时间线、标签、关键结论卡片和页脚说明。"
        if understanding.page_type == "landing_page":
            return "可以补充 CTA 按钮、对比卡片、用户反馈或页脚信息。"
        return "可以补充统计卡片、标签、CTA 按钮和简洁页脚。"

    def build_visual_direction(self, understanding: PageUnderstanding) -> str:
        mapping = {
            "clean": "整体风格偏清晰简洁，强调信息层级和可读性。",
            "academic": "整体风格偏理性和教学感，适合知识讲解与结构化阅读。",
            "showcase": "整体风格偏展示感和视觉吸引，适合突出亮点与重点内容。",
            "friendly": "整体风格偏轻松友好，适合降低阅读压力和提升亲近感。",
        }
        return mapping.get(understanding.style_direction, "整体风格偏清晰简洁，强调信息层级和可读性。")

    def build_layout_advice(self, understanding: PageUnderstanding) -> str:
        if understanding.page_type == "teaching_page":
            return "建议使用清晰的单栏或窄双栏布局，让内容按阅读顺序自然下滑。"
        if understanding.page_type == "summary_page":
            return "建议把概览放前、细节放中、总结放后，保持区块之间的节奏感。"
        if understanding.page_type == "landing_page":
            return "建议用更强的区块分隔和大标题布局，让页面有更明显的展示张力。"
        return "建议采用清楚的分区布局，让首屏概览和主体内容区块层次分明。"

    def build_interaction_hint(self, understanding: PageUnderstanding) -> str:
        if understanding.page_type == "teaching_page":
            return "可以加入锚点跳转或轻量折叠区块，帮助快速定位知识点。"
        if understanding.page_type == "summary_page":
            return "可以加入卡片 hover、高亮重点标签或小型折叠总结区块。"
        if understanding.page_type == "landing_page":
            return "可以加入按钮 hover、卡片悬停和轻量滚动出现效果。"
        return "可以加入基础 hover 效果和区块间的小过渡，提升浏览流畅度。"

    def build_starter_html(self, understanding: PageUnderstanding) -> str:
        title = understanding.page_topic
        hero_text = understanding.page_goal
        return (
            "<!DOCTYPE html>\n"
            "<html lang=\"zh-CN\">\n"
            "<head>\n"
            "  <meta charset=\"UTF-8\" />\n"
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
            f"  <title>{title}</title>\n"
            "</head>\n"
            "<body>\n"
            "  <header class=\"hero\">\n"
            f"    <h1>{title}</h1>\n"
            f"    <p>{hero_text}</p>\n"
            "  </header>\n"
            "  <main>\n"
            "    <section>\n"
            "      <h2>Overview</h2>\n"
            "      <p>在这里展示页面的核心内容概览。</p>\n"
            "    </section>\n"
            "    <section>\n"
            "      <h2>Main Content</h2>\n"
            "      <p>在这里补充主体区块内容。</p>\n"
            "    </section>\n"
            "  </main>\n"
            "  <footer>\n"
            "    <p>Generated by Visual Site Agent.</p>\n"
            "  </footer>\n"
            "</body>\n"
            "</html>"
        )
