-- ============================================
-- StudySolo MVP - Initial Database Schema
-- ============================================
-- NOTE: This file is for reference only.
-- Actual migrations are managed via Supabase MCP apply_migration.
-- Run `supabase migration fetch --yes` to sync from remote.
-- ============================================
-- Tables created:
--   Shared: user_profiles, subscriptions, addon_purchases,
--           payment_records, tier_change_log, student_verifications,
--           verification_codes_v2
--   StudySolo (ss_ prefix): ss_workflows, ss_workflow_runs, ss_usage_daily
-- ============================================

-- See remote migrations for actual DDL.
-- This file is kept as documentation of the original design intent.
